### ISSUE TITLE
latexspine.tex无法通过编译

### ISSUE THREAD

**Issue by PatriCui** [mohuangrui/latexspine#1]
\makespine提示Undefined control sequence.并且\rotatebox[origin=c]{-90}{~\LaTeX{}~}没有产生旋转效果

**Comment by mohuangrui** [comment]
你好，问题肯定是你的latex编译环境的问题，latex编译排错请见  [编译指南](https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97)

**Comment by mohuangrui** [comment]
对了， latexspine 建议用 xelatex 编译

**Comment by PatriCui** [comment]
测试了一下，我的环境没有问题，还是存在上述的问题。

**Comment by PatriCui** [comment]
其他的文档编译都是OK的，唯独书脊是无法正常编译通过的。

**Comment by mohuangrui** [comment]
麻烦你把 log 文件发过来吧

**Comment by PatriCui** [comment]
[latexspine.log](https://github.com/mohuangrui/latexspine/files/2054149/latexspine.log)
这是最新编译之后的生成的log文件，请查收。

**Comment by mohuangrui** [comment]
你好，问题发现是 ctex 更新中对 graphicx 的默认调用进行了调整，似乎最新版已不再默认调用，而我当时想着依赖 ctex 对 graphicx 的调用。
我已经更新，问题已修复，请测试， pdflatex，xelatex，luatex都可以。

**Comment by PatriCui** [comment]
好的，非常感谢

**Comment by mohuangrui** [comment]
非常感谢你发现这个问题

**Comment by PatriCui** [comment]
(^_^)
